# Generated by Django 6.0.1 on 2026-01-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('nombreBuque', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], default='pendiente', max_length=20)),
                ('infoVendedor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bandera', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestor_document.nave')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('puertoDestino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestor_document.puerto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='gestor_document.ruta')),
            ],
        ),
    ]
