# Generated by Django 6.0.1 on 2026-01-13 03:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='escala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestor_document.escala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='fechaSalida',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 12)),
        ),
    ]
