# Generated by Django 6.0.1 on 2026-01-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0002_documento_escala_ruta_fechasalida'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(fields=('nave', 'fechaSalida'), name='unique_nave_fecha'),
        ),
    ]
