# Generated by Django 6.0.1 on 2026-01-19 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0003_ruta_unique_nave_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='puertoDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_document.puerto'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_document.nave'),
        ),
    ]
