# Generated by Django 6.0.1 on 2026-01-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0004_alter_escala_puertodestino_alter_ruta_nave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='infoVendedor',
            new_name='infovendedor',
        ),
    ]
