# Generated by Django 6.0.1 on 2026-01-23 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0005_rename_infovendedor_documento_infovendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('BILL', 'BillOfLading'), ('MANIFIESTO', 'Manifiesto de carga'), ('CERTIFICADO', 'Certificado de origen')], max_length=11)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], db_default='pendiente', max_length=10)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentospdf', to='gestor_document.escala')),
            ],
        ),
    ]
