# Generated by Django 6.0.1 on 2026-01-31 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0006_documento_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'permissions': [('puede_crear_documentos', 'puede crear documentos'), ('puede_revisar_documentos', 'puede revisar documentos')]},
        ),
        migrations.AlterModelOptions(
            name='documento_pdf',
            options={'permissions': [('puede_crear_documentos', 'puede crear documentos'), ('puede_revisar_documentos', 'puede revisar documentos')]},
        ),
        migrations.CreateModel(
            name='perfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_document.puerto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
