# Generated by Django 6.0.1 on 2026-01-31 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_document', '0007_alter_documento_options_alter_documento_pdf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='puerto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_document.puerto'),
        ),
    ]
